apiVersion: v1
kind: ReplicationController
metadata:
  name: halloworld-contr
 
  labels:
    app: halloworld
    tier: app
spec:
  replicas: 3

  selector:
   app: halloworld
   tier: app
  # Pod Template
  template:
    metadata:
      labels:
        app: halloworld
        tier: app
    spec:
      containers:
      - name: application
        
        image: tawfik/cloud
    
        resources:
          
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          
        ports:
          
        - containerPort: 8080
         
